# Generated by Django 3.1.3 on 2021-02-01 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('feedback', models.CharField(max_length=1050, verbose_name='feedback')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.query')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(choices=[('chat', 'chat'), ('call', 'call'), ('query-assigned', 'query-assigned'), ('query-expired', 'query-expired'), ('admin', 'admin'), ('system', 'system')], max_length=64, verbose_name='type')),
                ('title', models.CharField(max_length=2048, verbose_name='title')),
                ('description', models.CharField(max_length=4096, verbose_name='description')),
                ('color', models.CharField(choices=[('info', 'info'), ('success', 'success'), ('error', 'error'), ('warning', 'warning'), ('primary', 'primary'), ('secondary', 'secondary')], max_length=64, verbose_name='color')),
                ('visited', models.BooleanField(default=False, verbose_name='is_visited')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ref', models.CharField(max_length=256, verbose_name='ref')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
