# Generated by Django 3.1.3 on 2021-02-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210201_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certificate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.certificate'),
        ),
    ]
