# Generated by Django 3.1.3 on 2021-02-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='qualifications'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialities',
            field=models.ManyToManyField(blank=True, related_name='specialities', to='accounts.Speciality'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(blank=True, default='39736137', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=6, verbose_name='gender'),
        ),
    ]
