# Generated by Django 3.1.7 on 2021-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210212_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
