# Generated by Django 3.1.3 on 2021-06-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_list', models.CharField(blank=True, max_length=100, null=True, verbose_name='Content List')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_heading', models.CharField(max_length=50, verbose_name='Blog Heading')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='Author')),
                ('abstract', models.TextField(blank=True, max_length=30, null=True, verbose_name='Abstract')),
                ('sub_heading', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub Heading')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
                ('sub_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.content', verbose_name='Sub Content')),
            ],
        ),
    ]
