# Generated by Django 3.1.3 on 2021-06-18 11:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rich_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
