# Generated by Django 3.1.3 on 2021-06-18 11:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_rich_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='rich_text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='sub_content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='sub_heading',
        ),
        migrations.AddField(
            model_name='blog',
            name='subcontent',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sub Content'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
