# Generated by Django 3.1.3 on 2021-06-24 08:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210618_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subcontent',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Sub Content'),
        ),
    ]
