# Generated by Django 3.1.3 on 2021-02-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=256, verbose_name='blood_pressure'),
        ),
        migrations.AlterField(
            model_name='query',
            name='current_medicine',
            field=models.CharField(blank=True, max_length=1024, verbose_name='current_medicine'),
        ),
        migrations.AlterField(
            model_name='query',
            name='height',
            field=models.CharField(blank=True, max_length=256, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='query',
            name='past_history',
            field=models.CharField(blank=True, max_length=4048, verbose_name='past_history'),
        ),
        migrations.AlterField(
            model_name='query',
            name='past_medical_history',
            field=models.CharField(blank=True, max_length=4048, verbose_name='past_medical_history'),
        ),
        migrations.AlterField(
            model_name='query',
            name='past_surgical_history',
            field=models.CharField(blank=True, max_length=4048, verbose_name='past_surgical_history'),
        ),
        migrations.AlterField(
            model_name='query',
            name='temperature',
            field=models.CharField(blank=True, max_length=256, verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='query',
            name='weight',
            field=models.CharField(blank=True, max_length=256, verbose_name='weight'),
        ),
    ]
