# Generated by Django 3.1.3 on 2021-02-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210210_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='amount',
            field=models.FloatField(),
        ),
    ]
